### ISSUE TITLE
关于compensation 

### ISSUE THREAD

**Issue by wkiulu** [psyrocloud/MS-SSIM_L1_LOSS#2]
请问这个项目是对Loss Functions for Image Restoration With Neural Networks这篇论文的实现吗？为什么在最后要✖️compensation，在原论文的实现里好像没看到。感谢回答

**Comment by Achilles-10** [comment]
同问

**Comment by psyrocloud** [comment]
这个项目是针对该论文的lua版本损失函数重新实现到pytorch上的。compensation是文献[2]和[3]中的技巧，用于平衡该损失函数和其他损失函数的权重。compensation的值可以根据实际需要自行更改；单独使用该损失函数时，应该对训练结果影响很小。
