### ISSUE TITLE
您好 很抱歉再次打扰您 还是想再次咨询您一下关于损失函数的问题

### ISSUE THREAD

**Issue by SUTwu** [psyrocloud/MS-SSIM_L1_LOSS#5]
您好  我是在PReNet去雨网络上想要实现该损失函数，该网络采用的是SSIM，我在使用MS-SSIM也可以正常运行，但是到L1或者L1-MS-SSIM的时候，就会出现离谱的数值。
因为对该损失函数非常急切想要应用，所以想再次请教您，不知道您知不知道这个原因。另外PReNet也在github中，很容易复现。

**Comment by psyrocloud** [comment]
> 您好 我是在PReNet去雨网络上想要实现该损失函数，该网络采用的是SSIM，我在使用MS-SSIM也可以正常运行，但是到L1或者L1-MS-SSIM的时候，就会出现离谱的数值。 因为对该损失函数非常急切想要应用，所以想再次请教您，不知道您知不知道这个原因。另外PReNet也在github中，很容易复现。

您好，我看了PReNet的带雨图像，这类图像很可能用L1和L2损失函数的效果都不会太好，论文原文也说MSE(L2)损失函数的效果很奇怪。这可能和雨水图像本身的性质有关系。您可以尝试将L1损失在L1-MS-SSIM损失中的比重进一步调小，如原来的0.5倍或0.1倍。

**Comment by SUTwu** [comment]
> > 您好 我是在PReNet去雨网络上想要实现该损失函数，该网络采用的是SSIM，我在使用MS-SSIM也可以正常运行，但是到L1或者L1-MS-SSIM的时候，就会出现离谱的数值。 因为对该损失函数非常急切想要应用，所以想再次请教您，不知道您知不知道这个原因。另外PReNet也在github中，很容易复现。
> 
> 您好，我看了PReNet的带雨图像，这类图像很可能用L1和L2损失函数的效果都不会太好，论文原文也说MSE(L2)损失函数的效果很奇怪。这可能和雨水图像本身的性质有关系。您可以尝试将L1损失在L1-MS-SSIM损失中的比重进一步调小，如原来的0.5倍或0.1倍。

非常感谢您的回复
