### ISSUE TITLE
Implementation of MSSSIM + L1 for Greyscale Images

### ISSUE THREAD

**Issue by willxxy** [psyrocloud/MS-SSIM_L1_LOSS#8]
Hi, thanks for the great implementation. I am currently working with greyscale images and implemented the loss for 1 channel images [here](https://github.com/willxxy/MS-SSIM-L1-For-1D/blob/main/msssim_l1.py). Would you mind looking at the implementation and see if it is accurate? 

Thank you.

**Comment by willxxy** [comment]
Hi, just another update on the implementation. I also implemented an option for a "mask." Please view it whenever you have time! Thank you.

**Comment by psyrocloud** [comment]
I think your implementation is okay. Alternatively, one can also make the gray image to a 3-channel image to fit the code (Although there might be some performance loss).
