### ISSUE TITLE
really slow

### ISSUE THREAD

**Issue by f-fuchs** [psyrocloud/MS-SSIM_L1_LOSS#9]
Hey,

thanks for your implementation.  When I am using this loss one epoch goes from taking around 30sec to taking over 20min. Did you experience a similar slow down? @psyrocloud @ashrithjacob

**Comment by psyrocloud** [comment]
Please be sure to use CUDA. This loss does heavy computations.

**Comment by f-fuchs** [comment]
I am using cuda in both runs. the first run is with l1loss from pytorch and takes around 30sec per epoch and with mixloss the same model takes around 30min per epoch.

what kind of slow down did you experience or would you think is typical/expected?
